import { SalesOrder, PurchaseOrder, SectorMoisture } from './types';

export const INITIAL_SALES_ORDERS: SalesOrder[] = [
  {
    id: 'so-1',
    orderNumber: '#SO-8821',
    timestamp: 'Today, 08:42 AM',
    triggerType: 'telemetry',
    telemetryRule: 'Telemetry Rule R-04: Sector 4B < 20%',
    telemetrySensor: 'Sensor Node #NS-04B-91 (17.8% SM)',
    soilMoisture: '17.8%',
    customerName: 'Ramesh Patel',
    landDetails: 'Plot 12-West • 40 Ha',
    serviceSku: 'Precision Irrigation Water (450 m³)',
    serviceDescription: 'Automated Pivot 03 Run',
    amount: 680.0,
    rateInfo: 'Rate: $1.51/m³',
    status: 'Auto-Generated',
    invoiceNumber: 'INV-1092',
    ndviScore: 0.74,
    fieldSnapshotUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAiWilS7O5saA811DKvdCTBfqWmTM_680mEINIPXEt6NOtyvPR5n5BzAVINLN12FHpLgv1IqHsYQPSvz4Ezh8KUyxlRywoFgCG8KdDYvg8v6jPFYphktBaPkb0gGBLGccTZxM06VH_aLCVHqDYoyeMM8XLAVASoAXULH91Z-y1btYmfzbC-vxkBgEZOR7meHk4vt9WLhwcvP0xe4qOxFo6uFvvclazEs25Xj1cvMrWnK-1oZm03zOFB9g',
  },
  {
    id: 'so-2',
    orderNumber: '#SO-8820',
    timestamp: 'Yesterday, 04:15 PM',
    triggerType: 'manual',
    telemetryRule: 'Manual Request',
    telemetrySensor: 'Field Tech: M. Jenkins',
    customerName: 'Sunita Devi',
    landDetails: 'Orchard Block 8 • 15 Ha',
    serviceSku: 'Drip Line Inspection Service',
    serviceDescription: 'Ultrasonic Emitter Diagnostic',
    amount: 240.0,
    rateInfo: 'Standard Tech Fee',
    status: 'Converted to Invoice',
    invoiceNumber: 'INV-1092',
    ndviScore: 0.81,
    fieldSnapshotUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAiWilS7O5saA811DKvdCTBfqWmTM_680mEINIPXEt6NOtyvPR5n5BzAVINLN12FHpLgv1IqHsYQPSvz4Ezh8KUyxlRywoFgCG8KdDYvg8v6jPFYphktBaPkb0gGBLGccTZxM06VH_aLCVHqDYoyeMM8XLAVASoAXULH91Z-y1btYmfzbC-vxkBgEZOR7meHk4vt9WLhwcvP0xe4qOxFo6uFvvclazEs25Xj1cvMrWnK-1oZm03zOFB9g',
  },
  {
    id: 'so-3',
    orderNumber: '#SO-8819',
    timestamp: 'Oct 24, 11:30 AM',
    triggerType: 'advisory',
    telemetryRule: 'Agronomy Advisory Schedule',
    telemetrySensor: 'Soil Nutrient Index Run',
    customerName: 'Vikram Singh',
    landDetails: 'Pinnacle Basins • 85 Ha',
    serviceSku: 'NPK Crop Advisory Run',
    serviceDescription: 'Prescription Mapping • 4 Zones',
    amount: 1150.0,
    rateInfo: 'Settled via Wire',
    status: 'Paid via Bank',
    paymentMethod: 'Wire Transfer #WT-8120',
    invoiceNumber: 'INV-1088',
    ndviScore: 0.69,
  },
  {
    id: 'so-4',
    orderNumber: '#SO-8818',
    timestamp: 'Oct 23, 02:10 PM',
    triggerType: 'telemetry',
    telemetryRule: 'Telemetry Rule R-02: Sector 2A < 18%',
    telemetrySensor: 'Sensor Node #NS-02A-14 (16.4% SM)',
    soilMoisture: '16.4%',
    customerName: 'Harpreet Gill',
    landDetails: 'Canal Ridge • 55 Ha',
    serviceSku: 'Deep Sub-surface Drip Flush (320 m³)',
    serviceDescription: 'Automated Sub-Zone 4 Purge',
    amount: 512.0,
    rateInfo: 'Rate: $1.60/m³',
    status: 'Auto-Generated',
    invoiceNumber: 'INV-1085',
    ndviScore: 0.72,
  },
  {
    id: 'so-5',
    orderNumber: '#SO-8817',
    timestamp: 'Oct 22, 09:15 AM',
    triggerType: 'manual',
    telemetryRule: 'Manual Contract Call-off',
    telemetrySensor: 'Dispatch Desk: K. Rao',
    customerName: 'Ananya Sharma',
    landDetails: 'Green Meadows • 30 Ha',
    serviceSku: 'Biological Pest Control Drone Spray',
    serviceDescription: 'Trichogramma Parasitoid Release',
    amount: 890.0,
    rateInfo: 'Fixed Drone Fee',
    status: 'Converted to Invoice',
    invoiceNumber: 'INV-1081',
    ndviScore: 0.78,
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-1',
    poNumber: '#PO-4402',
    createdDate: 'Created Oct 21',
    vendorName: 'AgriSupplies Co.',
    vendorId: 'Vendor ID: #VN-0092',
    products: 'NPK Fertilizer 50kg (120 Bags)',
    deliveryNotes: 'Delivered to Central Silo 2',
    totalCost: 6400.0,
    status: 'PO Confirmed',
    dueDate: 'Nov 05, 2024',
    paymentTerms: 'Net 15 Terms',
  },
  {
    id: 'po-2',
    poNumber: '#PO-4401',
    createdDate: 'Created Oct 18',
    vendorName: 'Indus Drip Tech Ltd',
    vendorId: 'Vendor ID: #VN-0184',
    products: 'Industrial Solenoid Valves (12 Units)',
    deliveryNotes: 'High-pressure brass 2-inch',
    totalCost: 1850.0,
    status: 'Bill Received',
    billNumber: '#VB-771',
    dueDate: 'Oct 30, 2024',
    paymentTerms: 'Due in 2 days',
    isUrgent: true,
  },
  {
    id: 'po-3',
    poNumber: '#PO-4399',
    createdDate: 'Created Oct 15',
    vendorName: 'State Water Utility Board',
    vendorId: 'Government Canal Concession',
    products: 'Bulk Reservoir Water Access',
    deliveryNotes: 'Quarterly Canal Allocation #Q3',
    totalCost: 12200.0,
    status: 'Payment Registered',
    dueDate: 'Paid Oct 20',
    paymentTerms: 'Check #CHQ-9901',
    paymentRef: 'CHQ-9901',
  },
  {
    id: 'po-4',
    poNumber: '#PO-4395',
    createdDate: 'Created Oct 12',
    vendorName: 'Global Micro-Nutrients Corp',
    vendorId: 'Vendor ID: #VN-0210',
    products: 'Chelated Zinc & Boron Solution (200L)',
    deliveryNotes: 'Fertigation Dosing Bay 1',
    totalCost: 3150.0,
    status: 'PO Confirmed',
    dueDate: 'Nov 02, 2024',
    paymentTerms: 'Net 20 Terms',
  },
];

export const MOCK_SECTORS: SectorMoisture[] = [
  {
    sectorId: 'SEC-4B',
    sectorName: 'Sector 4B (North Alluvium)',
    cropType: 'Wheat (Durum)',
    moisturePercent: 17.8,
    thresholdPercent: 20.0,
    pumpStatus: 'Armed',
    pivotId: 'Pivot 03',
    lastFlowM3: 450,
    lastReadingTime: '2 mins ago',
  },
  {
    sectorId: 'SEC-2A',
    sectorName: 'Sector 2A (Canal Ridge)',
    cropType: 'Cotton (Bt Hybrid)',
    moisturePercent: 18.2,
    thresholdPercent: 20.0,
    pumpStatus: 'Armed',
    pivotId: 'Pivot 01',
    lastFlowM3: 320,
    lastReadingTime: '4 mins ago',
  },
  {
    sectorId: 'SEC-1C',
    sectorName: 'Sector 1C (River Confluence)',
    cropType: 'Soybean (Glycine max)',
    moisturePercent: 28.5,
    thresholdPercent: 20.0,
    pumpStatus: 'Idle',
    pivotId: 'Pivot 02',
    lastFlowM3: 110,
    lastReadingTime: 'Just now',
  },
  {
    sectorId: 'SEC-3D',
    sectorName: 'Sector 3D (South Aquifer)',
    cropType: 'Maize (Yellow Corn)',
    moisturePercent: 32.1,
    thresholdPercent: 20.0,
    pumpStatus: 'Idle',
    pivotId: 'Drip System 05',
    lastFlowM3: 0,
    lastReadingTime: '10 mins ago',
  },
];

export const MOCK_LEDGER_POSTINGS = [
  {
    id: 'JRN-8840',
    date: '2024-10-24',
    document: 'INV-1088',
    description: 'Wire settlement Vikram Singh Agronomy Advisory',
    debitAccount: '1010 - State Agricultural Bank',
    creditAccount: '4020 - Agronomic Advisory Revenue',
    amount: 1150.0,
    status: 'Posted',
    balanced: true,
  },
  {
    id: 'JRN-8839',
    date: '2024-10-20',
    document: 'PO-4399',
    description: 'Quarterly Canal Concession Allocation settlement',
    debitAccount: '5010 - Water Utilities & Concession Expense',
    creditAccount: '1010 - State Agricultural Bank',
    amount: 12200.0,
    status: 'Posted',
    balanced: true,
  },
  {
    id: 'JRN-8838',
    date: '2024-10-18',
    document: 'VB-771',
    description: 'Vendor liability recognition Indus Drip Tech solenoid valves',
    debitAccount: '1300 - Irrigation Infrastructure Inventory',
    creditAccount: '2010 - Accounts Payable (Trade)',
    amount: 1850.0,
    status: 'Posted',
    balanced: true,
  },
];
